application: artf-gs
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /crossdomain\.xml
  static_files: static/root/crossdomain.xml
  upload: static/root/crossdomain.xml

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"