application: artf-server
version: 0-0-2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: test.app

libraries:
- name: jinja2
  version: "2.6"

- name: webapp2
  version: "2.5.2"
